name: pixup
description: "PixUp is a movie recommendation app that helps you discover the perfect films for your mood. Curated suggestions, seamless navigation, and a world of cinema at your fingertips."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  multi_select_flutter: ^4.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Italic.ttf
          style: italic

    - family: Inter Black
      fonts:
        - asset: assets/fonts/Inter_18pt-Black.ttf
        - asset: assets/fonts/Inter_18pt-BlackItalic.ttf
          style: italic
